server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    #Acá sera localhost por que tiene el port 8080
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/v1/**

        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/cars/v1/**

        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/api/bikes/v1/**
