
server:
  port: ${PORT:8081}
spring:
  cloud:
    config:
      server:
        git:
          # Es la rama donde tiene que mirar
          default-label: gateway
          #Es el repositorio
          uri: https://github.com/Lincol1999/Microservicio-con-Spring-Boot
          #Carpeta donde va a buscar
          search-paths:
            - config-data
  #El nombre
  application:
    name: config-service